# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        type: environment
        description: Select the environment
      maintenance_enable:
        type: boolean
        description: Maintenance
        required: true
      maintenance_message:
        description: 'Maintenance message'
        default: 'Hey boy! Im on maintenance'
        required: true

jobs:
  change_config:
    runs-on: ubuntu-latest
    
    steps:
    # Runs a single command using the runners shell
    - name: Change config
      run: |
        sudo su
        mkdir tmp
        cd tmp
        git clone https://github.com/JulienBouchardIT/testing-github-action.git
        cd testing-github-action
        git config user.name "Github actions"
        git remote remove origin
        git remote add origin https://${{ secrets.GIT_TOKEN }}@github.com/JulienBouchardIT/testing-github-action.git
        
        value=`cat test.json`
        value=`jq '.status.maintenance = ${{ github.event.inputs.maintenance_enable }}' <<<"$value"`
        value=`jq '.status.message = "${{ github.event.inputs.maintenance_message }}"' <<<"$value"`
        echo $value > 'test.json'
        
        git add .
        git commit -m "This is a scripted commit"
        git push --set-upstream origin main
