# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      environment:
        type: environment
        description: Select the environment
      maintenance_enable:
        type: boolean
        description: Maintenance
        required: true
      maintenance_message:
        description: 'Maintenance message'
        default: 'Hey boy! Im on maintenance'
        required: true

jobs:
  change_config:
    runs-on: ubuntu-latest
    
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: |
        if [ ${{ github.event.inputs.maintenance_enable }} ]
          then
            echo "Enable maintenance."
        fi
        echo "Message: ${{ github.event.inputs.maintenance_message }}"
        echo "waza"
